### ISSUE TITLE
Eltrade A300S KL

### ISSUE THREAD

**Issue by Ravenheart** [wqweto/UcsFiscalPrinters#1]
Здравейте,

Имате ли случайно документация за фискален принтер/касов апарат Eltrade A300S KL?

Намерих този документа, не знам дали е актуален към 2017 г.
https://github.com/wqweto/UcsFiscalPrinters/blob/master/Doc/eltrade_ecr---protocol_bulgaria.pdf

**Comment by wqweto** [comment]
Нямам представа, дали това е точния протокол за този модел каса и отдавна не следя Eltrade нито ги препоръчвам на клиенти.

При тях моделът на работа е "затворен" при което си продават детелината заедно с хардуерията и нямат никакво желание за интеграция с 3-rd party разработчици, което е ok за нас (и за тях вероятно).

**Comment by Ravenheart** [comment]
Ние принципно ползваме Datecs FP2000, но клиента ни в момента има само eltrade и иска с тях да продължава и сега се налага да пишем и за тях драйвер.
